name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      #show time
      - name: Show time
        run: date +"%Y-%m-%d %H:%M:%S %Z"
