# Basic Workflow

name: Simple CI job

on:

  push:
  pull_request:

  workflow_dispatch:

jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run time
        run: date +"%Y-%m-%d %H:%M:%S %Z"
