name: Maven Package

on:
  push:
    branches: [ "*" ]  # Запускать при пуше в любую ветку
  pull_request:
    branches: [ "main", "master" ]  # Запускать при ПР в main или master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn package -DskipTests

    - name: Verify JAR creation
      run: |
        if [ -f "target/*.jar" ]; then
          echo "JAR file created successfully"
          ls -la target/*.jar
        else
          echo "JAR file was not created"
          exit 1
        fi
