name: Maven Package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR creation
        run: |
          # Исправленная проверка наличия JAR-файлов
          if ls target/*.jar 1> /dev/null 2>&1; then
            echo "JAR file(s) created successfully"
            ls -la target/*.jar
          else
            echo "ERROR: JAR file was not created"
            echo "Contents of target directory:"
            ls -la target/
            exit 1
          fi